### ISSUE TITLE
一加五t无法启动黑域

### ISSUE THREAD

**Issue by leidian** [brevent/Brevent#495] opened 2019-01-01 06:11 UTC
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-yzz05mSyaLXhMicbeOubUA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '01-01 17:31:08.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '01-01 17:31:08.000' -d -s BreventLoader BreventServer
01-01 17:31:08.430 28952 28952 I BreventLoader: sdk: 28
01-01 17:31:08.470 28957 28957 I BreventLoader: pm path me.piebridge.brevent
01-01 17:31:08.536 28957 28957 I BreventLoader: line: package:/data/app/me.piebridge.brevent-yzz05mSyaLXhMicbeOubUA==/base.apk
01-01 17:31:08.538 28957 28957 I BreventLoader: loader path: /data/app/me.piebridge.brevent-yzz05mSyaLXhMicbeOubUA==/base.apk
01-01 17:31:08.539 28961 28961 I BreventLoader: start: 1546335068
01-01 17:31:09.248 28961 28961 I BreventServer: args: [10, me.piebridge.brevent, 1546335068]
01-01 17:31:09.295 28961 28961 I BreventServer: server log name: server.20190101.1731.28961.txt
01-01 17:31:09.295 28961 28961 I BreventServer: starting Brevent Server 3.5.8
01-01 17:31:09.322 28961 28961 I BreventServer: brevent version: 3.5.8
01-01 17:31:09.332 28961 28961 I BreventServer: brevent user: 0, uid: 2000
01-01 17:31:09.334 28961 28961 E BreventServer: Can't get running app processes
01-01 17:31:09.334 28961 28961 E BreventServer: for more information, refer https://github.com/brevent/Brevent/issues/491
01-01 17:31:09.356 28957 28957 E BreventLoader: worker 28961 exited with status 3
01-01 17:31:09.356 28957 28957 I BreventLoader: signal arrived, update: 0
01-01 17:31:09.357 28952 28952 I BreventLoader: worker 28957 exited with status 0
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by liudongmiao** [comment] 2019-01-01 09:20
duplicate of #491 , go there

**Closed as completed by liudongmiao** 2019-01-01 09:20 UTC
