### ISSUE TITLE
HI bug report

### ISSUE THREAD

**Issue by Zeozzz** [brevent/Brevent#494] opened 2019-01-01 02:17 UTC
adb server version (31) doesn't match this client (39); killing...
* daemon started successfully *
checking for server..started, pid: 29455
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-pSTyfFJAyngHmmZpbG-jsA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '01-01 10:14:32.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '01-01 10:14:32.000' -d -s BreventLoader BreventServer
01-01 10:14:32.012 29446 29446 I BreventLoader: sdk: 28
01-01 10:14:32.058 29451 29451 I BreventLoader: pm path me.piebridge.brevent
01-01 10:14:32.157 29451 29451 I BreventLoader: line: package:/data/app/me.piebridge.brevent-pSTyfFJAyngHmmZpbG-jsA==/base.apk
01-01 10:14:32.160 29451 29451 I BreventLoader: loader path: /data/app/me.piebridge.brevent-pSTyfFJAyngHmmZpbG-jsA==/base.apk
01-01 10:14:32.163 29455 29455 I BreventLoader: start: 1546308872
01-01 10:14:33.126 29455 29455 I BreventServer: args: [10, me.piebridge.brevent, 1546308872]
01-01 10:14:33.226 29455 29455 I BreventServer: server log name: server.20190101.1014.29455.txt
01-01 10:14:33.228 29455 29455 I BreventServer: starting Brevent Server 3.5.8
01-01 10:14:33.260 29455 29455 I BreventServer: brevent version: 3.5.8
01-01 10:14:33.283 29455 29455 I BreventServer: brevent user: 0, uid: 2000
01-01 10:14:33.293 29455 29455 E BreventServer: Can't get running app processes
01-01 10:14:33.293 29455 29455 E BreventServer: for more information, refer https://github.com/brevent/Brevent/issues/491
01-01 10:14:33.319 29451 29451 E BreventLoader: worker 29455 exited with status 3
01-01 10:14:33.319 29451 29451 I BreventLoader: signal arrived, update: 0
01-01 10:14:33.322 29446 29446 I BreventLoader: worker 29451 exited with status 0
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by liudongmiao** [comment] 2019-01-01 09:19
just as the link notified, refer to https://github.com/brevent/Brevent/issues/491

duplicate of #491

**Closed as completed by liudongmiao** 2019-01-01 09:19 UTC
